version: "3.3"
services:
  redis:
    image: "redis:alpine"
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_ADDRESS=redis:6379
      - PORT=5000
    command: "./my_cache listener"
  web:
    build: ./client/.
    ports:
      - "8002:3000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
